In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('../data/50_Startups.csv', delimiter=',')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          49 non-null float64
Administration     49 non-null float64
Marketing Spend    49 non-null float64
State              49 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [3]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      49.000000       49.000000        49.000000      50.000000
mean    74093.608776   121315.290408    215331.732449  112012.639200
std     46301.730529    28307.373863    119665.391550   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     38558.510000   103057.490000    134050.070000   90138.902500
50%     73994.560000   122616.840000    214634.810000  107978.190000
75%    101913.080000   145077.580000    299737.290000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

# Dealing With Null Data

In [4]:
dataset.isnull().any()

R&D Spend           True
Administration      True
Marketing Spend     True
State               True
Profit             False
dtype: bool

In [5]:
dataset.median()

R&D Spend           73994.56
Administration     122616.84
Marketing Spend    214634.81
Profit             107978.19
dtype: float64

In [6]:
dataset.loc[:, ['R&D Spend', 'Administration', 'Marketing Spend']] = dataset.loc[:, ['R&D Spend', 'Administration', 'Marketing Spend']].fillna(dataset.median())

In [7]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State               True
Profit             False
dtype: bool

#  Categorical Missing Sata

In [8]:
dataset.State.unique()

array(['New York', 'California', 'Florida', nan], dtype=object)

In [9]:
dataset.State.describe()

count           49
unique           3
top       New York
freq            17
Name: State, dtype: object

In [10]:
dataset.State.mode()[0]

'New York'

In [11]:
dataset.State.fillna(dataset.State.mode()[0], inplace=True)

In [12]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

# Dealing with Dummy Variabls

In [13]:
dataset = pd.get_dummies(dataset, drop_first = True)#dataset['State'], prefix = 'category', drop_first = True

In [14]:
dataset

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0   165349.20       136897.80        471784.10  192261.83              0   
1   162597.70       151377.59        443898.53  191792.06              0   
2   153441.51       101145.55        407934.54  191050.39              1   
3   144372.41       118671.85        383199.62  182901.99              0   
4   142107.34        91391.77        366168.42  166187.94              1   
5   131876.90        99814.71        362861.36  156991.12              0   
6   134615.46       147198.87        127716.82  156122.51              0   
7   130298.13       145530.06        323876.68  155752.60              1   
8   120542.52       148718.95        311613.29  152211.77              0   
9   123334.88       108679.17        304981.62  149759.96              0   
10  101913.08       110594.11        229160.95  146121.95              1   
11  100671.96        91790.61        249744.55  144259.40              0   
12   93863.75       127320.38        249839.44  141585.52              1   
13   91992.39       135495.07        252664.93  134307.35              0   
14  119943.24       156547.42        256512.92  132602.65              1   
15  114523.61       122616.84        261776.23  129917.04              0   
16   78013.11       121597.55        264346.06  126992.93              0   
17   94657.16       145077.58        282574.31  125370.37              0   
18   91749.16       114175.79        294919.57  124266.90              1   
19   86419.70       153514.11        214634.81  122776.86              0   
20   76253.86       113867.30        298664.47  118474.03              0   
21   78389.47       153773.43        299737.29  111313.02              0   
22   73994.56       122616.84        303319.26  110352.25              1   
23   67532.53       105751.03        304768.73  108733.99              1   
24   77044.01        99281.34        140574.81  108552.04              0   
25   64664.71       139553.16        137962.62  107404.34              0   
26   75328.87       144135.98        134050.07  105733.54              1   
27   72107.60       127864.55        353183.81  105008.31              0   
28   66051.52       182645.56        118148.20  103282.38              1   
29   65605.48       153032.06        107138.38  101004.64              0   
30   61994.48       115641.28         91131.24   99937.59              1   
31   61136.38       152701.92         88218.23   97483.56              0   
32   63408.86       129219.61         46085.25   97427.84              0   
33   73994.56       103057.49        214634.81   96778.92              1   
34   46426.07       157693.92        210797.67   96712.80              0   
35   46014.02        85047.44        205517.64   96479.51              0   
36   28663.76       127056.21        201126.82   90708.19              1   
37   44069.95        51283.14        197029.42   89949.14              0   
38   20229.59        65947.93        185265.10   81229.06              0   
39   38558.51        82982.09        174999.30   81005.76              0   
40   28754.33       118546.05        172795.67   78239.91              0   
41   27892.92        84710.77        164470.71   77798.83              1   
42   23640.93        96189.63        148001.11   71498.49              0   
43   15505.73       127382.30         35534.17   69758.98              0   
44   22177.74       154806.14         28334.72   65200.33              0   
45    1000.23       124153.04          1903.93   64926.08              0   
46    1315.46       115816.21        297114.46   49490.75              1   
47       0.00       135426.92             0.00   42559.73              0   
48     542.05        51743.15             0.00   35673.41              0   
49       0.00       116983.80         45173.06   14681.40              0   

    State_New York  
0                1  
1                0  
2                0  
3                1  
4                0  
5

#  Data Validation

In [15]:
dataset.drop(columns='Profit')

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               1
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11        214634.81              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122616.84        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   73994.56       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [16]:
X = dataset.drop(columns='Profit').values
y = dataset['Profit'].values.reshape(-1, 1)

#  Data Validation

In [17]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#  Data Scaling

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

# Model Training

In [19]:
from sklearn.linear_model import LinearRegression
MLR = LinearRegression()

MLR.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
MLR.intercept_, MLR.coef_ # w0, w1,..,w5

(array([4.34262726e-17]),
 array([[ 0.8560062 ,  0.02746304,  0.1355041 , -0.0240939 ,  0.01265784]]))

# Model Prediction

In [22]:
y_pred = MLR.predict(X_test)
y_pred

array([[-0.20304962],
       [ 0.54846668],
       [ 0.51239928],
       [-0.96253069],
       [ 1.6621197 ],
       [ 0.20033414],
       [-1.01923819],
       [-0.27829681],
       [ 0.09129264],
       [ 1.39389698]])

##  Inverse Scaling

In [23]:
sc_y.inverse_transform(y_pred)

array([[101229.90710752],
       [131640.52222306],
       [130181.03049651],
       [ 70496.99244654],
       [176705.24398542],
       [117553.10341926],
       [ 68202.28528884],
       [ 98184.97892362],
       [113140.66559627],
       [165851.43043571]])

# Model Validation 

In [24]:
import sklearn.metrics as mc

In [25]:
rms = np.sqrt(mc.mean_squared_error(y_test, y_pred))
print(rms)

127399.17641447148


In [ ]:
print('Thank You')